// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: monitor/v1/monitor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceProtocol int32

const (
	DeviceProtocol_DEVICE_PROTOCOL_UNSPECIFIED DeviceProtocol = 0
	DeviceProtocol_DEVICE_PROTOCOL_GRPC        DeviceProtocol = 1
	DeviceProtocol_DEVICE_PROTOCOL_REST        DeviceProtocol = 2
)

// Enum value maps for DeviceProtocol.
var (
	DeviceProtocol_name = map[int32]string{
		0: "DEVICE_PROTOCOL_UNSPECIFIED",
		1: "DEVICE_PROTOCOL_GRPC",
		2: "DEVICE_PROTOCOL_REST",
	}
	DeviceProtocol_value = map[string]int32{
		"DEVICE_PROTOCOL_UNSPECIFIED": 0,
		"DEVICE_PROTOCOL_GRPC":        1,
		"DEVICE_PROTOCOL_REST":        2,
	}
)

func (x DeviceProtocol) Enum() *DeviceProtocol {
	p := new(DeviceProtocol)
	*p = x
	return p
}

func (x DeviceProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_monitor_v1_monitor_proto_enumTypes[0].Descriptor()
}

func (DeviceProtocol) Type() protoreflect.EnumType {
	return &file_monitor_v1_monitor_proto_enumTypes[0]
}

func (x DeviceProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceProtocol.Descriptor instead.
func (DeviceProtocol) EnumDescriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{0}
}

type DeviceStatus int32

const (
	DeviceStatus_DEVICE_STATUS_UNSPECIFIED DeviceStatus = 0
	DeviceStatus_DEVICE_STATUS_UP          DeviceStatus = 1
	DeviceStatus_DEVICE_STATUS_DOWN        DeviceStatus = 2
	DeviceStatus_DEVICE_STATUS_DEGRADED    DeviceStatus = 3
)

// Enum value maps for DeviceStatus.
var (
	DeviceStatus_name = map[int32]string{
		0: "DEVICE_STATUS_UNSPECIFIED",
		1: "DEVICE_STATUS_UP",
		2: "DEVICE_STATUS_DOWN",
		3: "DEVICE_STATUS_DEGRADED",
	}
	DeviceStatus_value = map[string]int32{
		"DEVICE_STATUS_UNSPECIFIED": 0,
		"DEVICE_STATUS_UP":          1,
		"DEVICE_STATUS_DOWN":        2,
		"DEVICE_STATUS_DEGRADED":    3,
	}
)

func (x DeviceStatus) Enum() *DeviceStatus {
	p := new(DeviceStatus)
	*p = x
	return p
}

func (x DeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_monitor_v1_monitor_proto_enumTypes[1].Descriptor()
}

func (DeviceStatus) Type() protoreflect.EnumType {
	return &file_monitor_v1_monitor_proto_enumTypes[1]
}

func (x DeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceStatus.Descriptor instead.
func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{1}
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Protocol      DeviceProtocol         `protobuf:"varint,4,opt,name=protocol,proto3,enum=monitor.v1.DeviceProtocol" json:"protocol,omitempty"`
	Status        DeviceStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=monitor.v1.DeviceStatus" json:"status,omitempty"`
	LastChecked   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	Capabilities  []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Device) GetProtocol() DeviceProtocol {
	if x != nil {
		return x.Protocol
	}
	return DeviceProtocol_DEVICE_PROTOCOL_UNSPECIFIED
}

func (x *Device) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

func (x *Device) GetLastChecked() *timestamppb.Timestamp {
	if x != nil {
		return x.LastChecked
	}
	return nil
}

func (x *Device) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Diagnostics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	HardwareVersion string                 `protobuf:"bytes,2,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	SoftwareVersion string                 `protobuf:"bytes,3,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,4,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	Status          DeviceStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=monitor.v1.DeviceStatus" json:"status,omitempty"`
	Checksum        string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	CollectedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Diagnostics) Reset() {
	*x = Diagnostics{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostics) ProtoMessage() {}

func (x *Diagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostics.ProtoReflect.Descriptor instead.
func (*Diagnostics) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *Diagnostics) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Diagnostics) GetHardwareVersion() string {
	if x != nil {
		return x.HardwareVersion
	}
	return ""
}

func (x *Diagnostics) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *Diagnostics) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *Diagnostics) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

func (x *Diagnostics) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Diagnostics) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{2}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceResponse) Reset() {
	*x = GetDeviceResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResponse) ProtoMessage() {}

func (x *GetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type GetDiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiagnosticsRequest) Reset() {
	*x = GetDiagnosticsRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsRequest) ProtoMessage() {}

func (x *GetDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *GetDiagnosticsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetDiagnosticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagnostics   *Diagnostics           `protobuf:"bytes,1,opt,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiagnosticsResponse) Reset() {
	*x = GetDiagnosticsResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsResponse) ProtoMessage() {}

func (x *GetDiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *GetDiagnosticsResponse) GetDiagnostics() *Diagnostics {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type AddDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Protocol      DeviceProtocol         `protobuf:"varint,4,opt,name=protocol,proto3,enum=monitor.v1.DeviceProtocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDeviceRequest) Reset() {
	*x = AddDeviceRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceRequest) ProtoMessage() {}

func (x *AddDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeviceRequest.ProtoReflect.Descriptor instead.
func (*AddDeviceRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{8}
}

func (x *AddDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddDeviceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddDeviceRequest) GetProtocol() DeviceProtocol {
	if x != nil {
		return x.Protocol
	}
	return DeviceProtocol_DEVICE_PROTOCOL_UNSPECIFIED
}

type AddDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDeviceResponse) Reset() {
	*x = AddDeviceResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceResponse) ProtoMessage() {}

func (x *AddDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeviceResponse.ProtoReflect.Descriptor instead.
func (*AddDeviceResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *AddDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type RemoveDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDeviceRequest) Reset() {
	*x = RemoveDeviceRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDeviceRequest) ProtoMessage() {}

func (x *RemoveDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDeviceRequest.ProtoReflect.Descriptor instead.
func (*RemoveDeviceRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type RemoveDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDeviceResponse) Reset() {
	*x = RemoveDeviceResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDeviceResponse) ProtoMessage() {}

func (x *RemoveDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDeviceResponse.ProtoReflect.Descriptor instead.
func (*RemoveDeviceResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{11}
}

// Device-facing diagnostics service. gRPC devices that want to expose
// diagnostics implement this convention and advertise it via the standard
// gRPC health service (service name "device.Diagnostics").
type CollectDiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectDiagnosticsRequest) Reset() {
	*x = CollectDiagnosticsRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectDiagnosticsRequest) ProtoMessage() {}

func (x *CollectDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*CollectDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{12}
}

type CollectDiagnosticsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HardwareVersion string                 `protobuf:"bytes,1,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	SoftwareVersion string                 `protobuf:"bytes,2,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,3,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	Status          DeviceStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=monitor.v1.DeviceStatus" json:"status,omitempty"`
	Checksum        string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CollectDiagnosticsResponse) Reset() {
	*x = CollectDiagnosticsResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectDiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectDiagnosticsResponse) ProtoMessage() {}

func (x *CollectDiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectDiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*CollectDiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{13}
}

func (x *CollectDiagnosticsResponse) GetHardwareVersion() string {
	if x != nil {
		return x.HardwareVersion
	}
	return ""
}

func (x *CollectDiagnosticsResponse) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *CollectDiagnosticsResponse) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *CollectDiagnosticsResponse) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

func (x *CollectDiagnosticsResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

var File_monitor_v1_monitor_proto protoreflect.FileDescriptor

const file_monitor_v1_monitor_proto_rawDesc = "" +
	"\n" +
	"\x18monitor/v1/monitor.proto\x12\n" +
	"monitor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x02\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x126\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x1a.monitor.v1.DeviceProtocolR\bprotocol\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.monitor.v1.DeviceStatusR\x06status\x12=\n" +
	"\flast_checked\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vlastChecked\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\"\xb8\x02\n" +
	"\vDiagnostics\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12)\n" +
	"\x10hardware_version\x18\x02 \x01(\tR\x0fhardwareVersion\x12)\n" +
	"\x10software_version\x18\x03 \x01(\tR\x0fsoftwareVersion\x12)\n" +
	"\x10firmware_version\x18\x04 \x01(\tR\x0ffirmwareVersion\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.monitor.v1.DeviceStatusR\x06status\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12=\n" +
	"\fcollected_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\"\x14\n" +
	"\x12ListDevicesRequest\"C\n" +
	"\x13ListDevicesResponse\x12,\n" +
	"\adevices\x18\x01 \x03(\v2\x12.monitor.v1.DeviceR\adevices\"/\n" +
	"\x10GetDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"?\n" +
	"\x11GetDeviceResponse\x12*\n" +
	"\x06device\x18\x01 \x01(\v2\x12.monitor.v1.DeviceR\x06device\"4\n" +
	"\x15GetDiagnosticsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"S\n" +
	"\x16GetDiagnosticsResponse\x129\n" +
	"\vdiagnostics\x18\x01 \x01(\v2\x17.monitor.v1.DiagnosticsR\vdiagnostics\"\x88\x01\n" +
	"\x10AddDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x126\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x1a.monitor.v1.DeviceProtocolR\bprotocol\"?\n" +
	"\x11AddDeviceResponse\x12*\n" +
	"\x06device\x18\x01 \x01(\v2\x12.monitor.v1.DeviceR\x06device\"2\n" +
	"\x13RemoveDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\x16\n" +
	"\x14RemoveDeviceResponse\"\x1b\n" +
	"\x19CollectDiagnosticsRequest\"\xeb\x01\n" +
	"\x1aCollectDiagnosticsResponse\x12)\n" +
	"\x10hardware_version\x18\x01 \x01(\tR\x0fhardwareVersion\x12)\n" +
	"\x10software_version\x18\x02 \x01(\tR\x0fsoftwareVersion\x12)\n" +
	"\x10firmware_version\x18\x03 \x01(\tR\x0ffirmwareVersion\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.monitor.v1.DeviceStatusR\x06status\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum*e\n" +
	"\x0eDeviceProtocol\x12\x1f\n" +
	"\x1bDEVICE_PROTOCOL_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DEVICE_PROTOCOL_GRPC\x10\x01\x12\x18\n" +
	"\x14DEVICE_PROTOCOL_REST\x10\x02*w\n" +
	"\fDeviceStatus\x12\x1d\n" +
	"\x19DEVICE_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DEVICE_STATUS_UP\x10\x01\x12\x16\n" +
	"\x12DEVICE_STATUS_DOWN\x10\x02\x12\x1a\n" +
	"\x16DEVICE_STATUS_DEGRADED\x10\x032m\n" +
	"\x11DeviceDiagnostics\x12X\n" +
	"\aCollect\x12%.monitor.v1.CollectDiagnosticsRequest\x1a&.monitor.v1.CollectDiagnosticsResponse2\xa0\x03\n" +
	"\x0eMonitorService\x12N\n" +
	"\vListDevices\x12\x1e.monitor.v1.ListDevicesRequest\x1a\x1f.monitor.v1.ListDevicesResponse\x12H\n" +
	"\tGetDevice\x12\x1c.monitor.v1.GetDeviceRequest\x1a\x1d.monitor.v1.GetDeviceResponse\x12W\n" +
	"\x0eGetDiagnostics\x12!.monitor.v1.GetDiagnosticsRequest\x1a\".monitor.v1.GetDiagnosticsResponse\x12H\n" +
	"\tAddDevice\x12\x1c.monitor.v1.AddDeviceRequest\x1a\x1d.monitor.v1.AddDeviceResponse\x12Q\n" +
	"\fRemoveDevice\x12\x1f.monitor.v1.RemoveDeviceRequest\x1a .monitor.v1.RemoveDeviceResponseB\x16Z\x14ubi/proto/monitor/v1b\x06proto3"

var (
	file_monitor_v1_monitor_proto_rawDescOnce sync.Once
	file_monitor_v1_monitor_proto_rawDescData []byte
)

func file_monitor_v1_monitor_proto_rawDescGZIP() []byte {
	file_monitor_v1_monitor_proto_rawDescOnce.Do(func() {
		file_monitor_v1_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_v1_monitor_proto_rawDesc), len(file_monitor_v1_monitor_proto_rawDesc)))
	})
	return file_monitor_v1_monitor_proto_rawDescData
}

var file_monitor_v1_monitor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_monitor_v1_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_monitor_v1_monitor_proto_goTypes = []any{
	(DeviceProtocol)(0),                // 0: monitor.v1.DeviceProtocol
	(DeviceStatus)(0),                  // 1: monitor.v1.DeviceStatus
	(*Device)(nil),                     // 2: monitor.v1.Device
	(*Diagnostics)(nil),                // 3: monitor.v1.Diagnostics
	(*ListDevicesRequest)(nil),         // 4: monitor.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),        // 5: monitor.v1.ListDevicesResponse
	(*GetDeviceRequest)(nil),           // 6: monitor.v1.GetDeviceRequest
	(*GetDeviceResponse)(nil),          // 7: monitor.v1.GetDeviceResponse
	(*GetDiagnosticsRequest)(nil),      // 8: monitor.v1.GetDiagnosticsRequest
	(*GetDiagnosticsResponse)(nil),     // 9: monitor.v1.GetDiagnosticsResponse
	(*AddDeviceRequest)(nil),           // 10: monitor.v1.AddDeviceRequest
	(*AddDeviceResponse)(nil),          // 11: monitor.v1.AddDeviceResponse
	(*RemoveDeviceRequest)(nil),        // 12: monitor.v1.RemoveDeviceRequest
	(*RemoveDeviceResponse)(nil),       // 13: monitor.v1.RemoveDeviceResponse
	(*CollectDiagnosticsRequest)(nil),  // 14: monitor.v1.CollectDiagnosticsRequest
	(*CollectDiagnosticsResponse)(nil), // 15: monitor.v1.CollectDiagnosticsResponse
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
}
var file_monitor_v1_monitor_proto_depIdxs = []int32{
	0,  // 0: monitor.v1.Device.protocol:type_name -> monitor.v1.DeviceProtocol
	1,  // 1: monitor.v1.Device.status:type_name -> monitor.v1.DeviceStatus
	16, // 2: monitor.v1.Device.last_checked:type_name -> google.protobuf.Timestamp
	1,  // 3: monitor.v1.Diagnostics.status:type_name -> monitor.v1.DeviceStatus
	16, // 4: monitor.v1.Diagnostics.collected_at:type_name -> google.protobuf.Timestamp
	2,  // 5: monitor.v1.ListDevicesResponse.devices:type_name -> monitor.v1.Device
	2,  // 6: monitor.v1.GetDeviceResponse.device:type_name -> monitor.v1.Device
	3,  // 7: monitor.v1.GetDiagnosticsResponse.diagnostics:type_name -> monitor.v1.Diagnostics
	0,  // 8: monitor.v1.AddDeviceRequest.protocol:type_name -> monitor.v1.DeviceProtocol
	2,  // 9: monitor.v1.AddDeviceResponse.device:type_name -> monitor.v1.Device
	1,  // 10: monitor.v1.CollectDiagnosticsResponse.status:type_name -> monitor.v1.DeviceStatus
	14, // 11: monitor.v1.DeviceDiagnostics.Collect:input_type -> monitor.v1.CollectDiagnosticsRequest
	4,  // 12: monitor.v1.MonitorService.ListDevices:input_type -> monitor.v1.ListDevicesRequest
	6,  // 13: monitor.v1.MonitorService.GetDevice:input_type -> monitor.v1.GetDeviceRequest
	8,  // 14: monitor.v1.MonitorService.GetDiagnostics:input_type -> monitor.v1.GetDiagnosticsRequest
	10, // 15: monitor.v1.MonitorService.AddDevice:input_type -> monitor.v1.AddDeviceRequest
	12, // 16: monitor.v1.MonitorService.RemoveDevice:input_type -> monitor.v1.RemoveDeviceRequest
	15, // 17: monitor.v1.DeviceDiagnostics.Collect:output_type -> monitor.v1.CollectDiagnosticsResponse
	5,  // 18: monitor.v1.MonitorService.ListDevices:output_type -> monitor.v1.ListDevicesResponse
	7,  // 19: monitor.v1.MonitorService.GetDevice:output_type -> monitor.v1.GetDeviceResponse
	9,  // 20: monitor.v1.MonitorService.GetDiagnostics:output_type -> monitor.v1.GetDiagnosticsResponse
	11, // 21: monitor.v1.MonitorService.AddDevice:output_type -> monitor.v1.AddDeviceResponse
	13, // 22: monitor.v1.MonitorService.RemoveDevice:output_type -> monitor.v1.RemoveDeviceResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_monitor_v1_monitor_proto_init() }
func file_monitor_v1_monitor_proto_init() {
	if File_monitor_v1_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_v1_monitor_proto_rawDesc), len(file_monitor_v1_monitor_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_monitor_v1_monitor_proto_goTypes,
		DependencyIndexes: file_monitor_v1_monitor_proto_depIdxs,
		EnumInfos:         file_monitor_v1_monitor_proto_enumTypes,
		MessageInfos:      file_monitor_v1_monitor_proto_msgTypes,
	}.Build()
	File_monitor_v1_monitor_proto = out.File
	file_monitor_v1_monitor_proto_goTypes = nil
	file_monitor_v1_monitor_proto_depIdxs = nil
}
